export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_STARTUPS_SUCCESS = 'LOAD_STARTUPS_SUCCESS';
export const CREATE_STARTUP_SUCCESS = 'CREATE_STARTUP_SUCCESS';
export const UPDATE_STARTUP_SUCCESS = 'UPDATE_STARTUP_SUCCESS';

export const LOAD_INDUSTRIES_SUCCESS = 'LOAD_INDUSTRIES_SUCCESS';
